// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPLOADING_FILE.Context;

namespace UPLOADING_FILE.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("UPLOADING_FILE.Models.FileOnDataBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.Property<string>("prolongation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileOnDataBaseModel");
                });

            modelBuilder.Entity("UPLOADING_FILE.Models.FileOnFileSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.Property<string>("prolongation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileOnFileSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
